/* ========================================
   Briu Dynamic Stats
   Reads from stats.json (updated by GitHub Action),
   computed dates, timeline "Today"
   ======================================== */
(function() {
  'use strict';
  var CACHE_KEY = 'briu_gh_stats';
  var CACHE_TTL = 3600000; // 1 hour
  var FIRST_COMMIT = new Date('2026-02-10T00:00:00-08:00');

  function pacificNow() {
    return new Date(new Date().toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }));
  }

  function daysSince(date) {
    return Math.floor((pacificNow() - date) / 86400000);
  }

  function formatDate(d) {
    var m = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return m[d.getMonth()] + ' ' + d.getDate();
  }

  function updateEls(key, value) {
    var els = document.querySelectorAll('[data-dynamic="' + key + '"]');
    for (var i = 0; i < els.length; i++) {
      els[i].textContent = value;
      if (els[i].hasAttribute('data-count')) els[i].setAttribute('data-count', value);
    }
  }

  function updateComputed() {
    var buildDays = daysSince(FIRST_COMMIT);

    updateEls('build-days', buildDays);

    // Update commit-days labels
    var labels = document.querySelectorAll('[data-dynamic-label="commit-days"]');
    for (var i = 0; i < labels.length; i++) {
      labels[i].textContent = 'Changes Shipped';
    }

    // Add "Today" to timeline
    var vtl = document.querySelector('.vtl');
    if (vtl && !document.getElementById('vtl-today')) {
      var today = pacificNow();
      var entry = document.createElement('div');
      entry.className = 'vtl-entry';
      entry.id = 'vtl-today';
      entry.setAttribute('data-category', 'business');
      entry.innerHTML =
        '<div class="vtl-dot" style="background:var(--forest);box-shadow:0 0 0 4px rgba(77,128,112,0.2),0 0 12px rgba(77,128,112,0.3)"></div>' +
        '<div class="vtl-card" style="border-color:rgba(77,128,112,0.2)">' +
        '<div class="vtl-date" style="color:var(--forest)">' + formatDate(today) + '</div>' +
        '<div class="vtl-title">Today</div>' +
        '<div class="vtl-desc">Day ' + buildDays + ' of building with agents.</div>' +
        '</div>';
      vtl.appendChild(entry);
    }

    // Update "Last updated" timestamp
    var meta = document.querySelector('.stats-meta');
    if (meta) meta.textContent = 'Live dashboard · Updated ' + formatDate(pacificNow()) + ', ' + pacificNow().getFullYear() + ' PT';
  }

  function fetchStats() {
    try {
      var cached = JSON.parse(localStorage.getItem(CACHE_KEY));
      if (cached && Date.now() - cached.ts < CACHE_TTL) {
        applyStats(cached);
        return;
      }
    } catch(e) {}

    // Fetch from stats.json (generated by GitHub Action)
    fetch('/stats.json?v=' + Date.now())
      .then(function(r) { return r.json(); })
      .then(function(data) {
        if (!data || !data.totalCommits) return;
        data.ts = Date.now();
        try { localStorage.setItem(CACHE_KEY, JSON.stringify(data)); } catch(e) {}
        applyStats(data);
      })
      .catch(function() { /* fail silently, keep hardcoded defaults */ });
  }

  function applyStats(data) {
    updateEls('commits', data.totalCommits.toLocaleString());
    if (data.websiteCommits) updateEls('website-commits', data.websiteCommits.toLocaleString());
    if (data.privateAgentCommits) updateEls('agent-commits', data.privateAgentCommits.toLocaleString());
    if (data.linesOfCode) updateEls('lines-of-code', data.linesOfCode.toLocaleString());
    if (data.chartCount) updateEls('chart-count', data.chartCount.toLocaleString());
    if (data.articleCount) updateEls('article-count', data.articleCount.toLocaleString());
    if (data.wordsOfContent) updateEls('words-of-content', data.wordsOfContent.toLocaleString());
    if (data.pageCount) updateEls('page-count', data.pageCount.toLocaleString());
  }

  function init() {
    updateComputed();
    fetchStats();
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
