/* ========================================
   Briu Dynamic Stats
   Reads from stats.json (updated by GitHub Action),
   computed dates, timeline "Today"
   ======================================== */
(function() {
  'use strict';
  var CACHE_KEY = 'briu_gh_stats';
  var CACHE_TTL = 3600000; // 1 hour
  var FIRST_COMMIT = new Date('2026-02-10T00:00:00-08:00');

  // ─── Single source of truth for all stat fallbacks ───
  // These are used to initialize all data-dynamic elements on page load
  // before stats.json arrives. Update here when numbers change.
  var FALLBACKS = {
    commits:           740,   // totalCommits (website + agent repos)
    websiteCommits:    440,   // website repo only (ljcairns/briu-website)
    linesOfCode:       '17.7K', // total (website + agent)
    avgDailyCost:      '$29\u201339', // full stack: API + Claude Max + ChatGPT Pro + VPS
    peakDailyCost:     '$138.84',
    totalApiSpend:     '$550.00',
    agentSkills:       12,    // live skills in production
    // Security — scoped to sanitizer red-team taxonomy
    secDefenseLayers:            10,
    secOpenBypasses:             0,
    secBypassesClosed:           290
  };

  function pacificNow() {
    return new Date(new Date().toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }));
  }

  function daysSince(date) {
    return Math.floor((pacificNow() - date) / 86400000);
  }

  function formatDate(d) {
    var m = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return m[d.getMonth()] + ' ' + d.getDate();
  }

  function updateEls(key, value) {
    var els = document.querySelectorAll('[data-dynamic="' + key + '"]');
    for (var i = 0; i < els.length; i++) {
      els[i].textContent = value;
      if (els[i].hasAttribute('data-count')) els[i].setAttribute('data-count', value);
    }
  }

  function initFallbacks() {
    updateEls('commits',              FALLBACKS.commits.toLocaleString());
    updateEls('website-commits',      FALLBACKS.websiteCommits.toLocaleString());
    updateEls('lines-of-code',        FALLBACKS.linesOfCode);
    updateEls('avg-daily-cost',       FALLBACKS.avgDailyCost);
    updateEls('peak-daily-cost',      FALLBACKS.peakDailyCost);
    updateEls('total-api-spend',      FALLBACKS.totalApiSpend);
    updateEls('agent-skills',         FALLBACKS.agentSkills);
    updateEls('sec-defense-layers',   FALLBACKS.secDefenseLayers);
    updateEls('sec-open-bypasses',    FALLBACKS.secOpenBypasses);
    updateEls('sec-bypasses-closed',  FALLBACKS.secBypassesClosed);
  }

  function updateComputed() {
    var buildDays = daysSince(FIRST_COMMIT);

    updateEls('build-days', buildDays);

    // Update commit-days labels
    var labels = document.querySelectorAll('[data-dynamic-label="commit-days"]');
    for (var i = 0; i < labels.length; i++) {
      labels[i].textContent = 'Changes Shipped';
    }

    // Add "Today" to timeline
    var vtl = document.querySelector('.vtl');
    if (vtl && !document.getElementById('vtl-today')) {
      var today = pacificNow();
      var entry = document.createElement('div');
      entry.className = 'vtl-entry';
      entry.id = 'vtl-today';
      entry.setAttribute('data-category', 'business');
      entry.innerHTML =
        '<div class="vtl-dot" style="background:var(--forest);box-shadow:0 0 0 4px rgba(77,128,112,0.2),0 0 12px rgba(77,128,112,0.3)"></div>' +
        '<div class="vtl-card" style="border-color:rgba(77,128,112,0.2)">' +
        '<div class="vtl-date" style="color:var(--forest)">' + formatDate(today) + '</div>' +
        '<div class="vtl-title">Today</div>' +
        '<div class="vtl-desc">Day ' + buildDays + ' of building with agents.</div>' +
        '</div>';
      vtl.appendChild(entry);
    }

    // Update "Last updated" timestamp
    var meta = document.querySelector('.stats-meta');
    if (meta) meta.textContent = 'Live dashboard · Updated ' + formatDate(pacificNow()) + ', ' + pacificNow().getFullYear() + ' PT';
  }

  function fetchStats() {
    try {
      var cached = JSON.parse(localStorage.getItem(CACHE_KEY));
      if (cached && Date.now() - cached.ts < CACHE_TTL) {
        applyStats(cached);
        return;
      }
    } catch(e) {}

    // Fetch from stats.json (generated by GitHub Action)
    fetch('/stats.json?v=' + Date.now())
      .then(function(r) { return r.json(); })
      .then(function(data) {
        if (!data || !data.totalCommits) return;
        data.ts = Date.now();
        try { localStorage.setItem(CACHE_KEY, JSON.stringify(data)); } catch(e) {}
        applyStats(data);
      })
      .catch(function() { /* fail silently, keep hardcoded defaults */ });
  }

  function applyStats(data) {
    updateEls('commits', data.totalCommits.toLocaleString());
    if (data.websiteCommits) updateEls('website-commits', data.websiteCommits.toLocaleString());
    if (data.linesOfCode) {
      var loc = data.linesOfCode >= 1000 ? (data.linesOfCode / 1000).toFixed(1) + 'K' : data.linesOfCode.toLocaleString();
      updateEls('lines-of-code', loc);
    }
    if (data.agentSkills) updateEls('agent-skills', data.agentSkills);
    if (data.avgDailyCost) {
      updateEls('avg-daily-cost', '$' + data.avgDailyCost.toFixed(2));
    }
    if (data.peakDailyCost) updateEls('peak-daily-cost', '$' + data.peakDailyCost.toFixed(2));
    if (data.totalApiSpend) updateEls('total-api-spend', '$' + data.totalApiSpend.toFixed(2));
  }

  // ─── Site Config (pricing, costs, build stats) ───
  function resolveConfigPath(obj, path) {
    var parts = path.split('.');
    for (var i = 0; i < parts.length; i++) {
      if (!obj || typeof obj !== 'object') return undefined;
      obj = obj[parts[i]];
    }
    return obj;
  }

  function formatConfigValue(val, el) {
    if (val === undefined || val === null) return '';
    var fmt = el.getAttribute('data-config-format');
    if (fmt === 'dollar' && typeof val === 'number') return '$' + val.toLocaleString();
    if (fmt === 'dollar-mo' && typeof val === 'number') return '$' + val.toLocaleString() + '/mo';
    if (fmt === 'dollar-day') return '$' + val + '/day';
    return String(val);
  }

  function loadConfig() {
    fetch('/site-config.json?v=' + Date.now())
      .then(function(r) { return r.json(); })
      .then(function(cfg) {
        var els = document.querySelectorAll('[data-config]');
        for (var i = 0; i < els.length; i++) {
          var path = els[i].getAttribute('data-config');
          var val = resolveConfigPath(cfg, path);
          if (val !== undefined) {
            var display = formatConfigValue(val, els[i]);
            els[i].textContent = display;
            if (els[i].hasAttribute('data-count')) els[i].setAttribute('data-count', val);
          }
        }
      })
      .catch(function() { /* fail silently, keep hardcoded defaults */ });
  }

  // ─── Security Metrics (manually maintained, separate from auto-updated stats) ───
  function loadSecurityMetrics() {
    fetch('/security-metrics.json?v=' + Date.now())
      .then(function(r) { return r.json(); })
      .then(function(sec) {
        if (!sec) return;
        if (sec.defenseLayers !== undefined)           updateEls('sec-defense-layers',   sec.defenseLayers);
        if (sec.openKnownSanitizerBypasses !== undefined) updateEls('sec-open-bypasses', sec.openKnownSanitizerBypasses);
        if (sec.knownSanitizerBypassesClosed !== undefined) updateEls('sec-bypasses-closed', sec.knownSanitizerBypassesClosed);
        // Update any tooltip data-attributes that reference security stats
        var hudSec = document.getElementById('hud-open-bypasses');
        if (hudSec && sec.lastRedTeamDate) {
          var tip = hudSec.closest('[data-tooltip]');
          if (tip) tip.setAttribute('data-tooltip',
            'Known sanitizer bypasses within our current red-team taxonomy · Last tested ' + sec.lastRedTeamDate);
        }
      })
      .catch(function() { /* fail silently, keep FALLBACKS */ });
  }

  function init() {
    initFallbacks();   // immediate — no flicker, no stale hardcodes
    updateComputed();
    fetchStats();
    loadConfig();
    loadSecurityMetrics();
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
